package main

import (
	"fmt"
	"os"
	"reflect"
	"strings"

	"github.com/jpalaniselvam/myna/internal/types"
)

// List of types to generate
// Add all exported structs here
var typeRegistry = []interface{}{
	types.Metadata{},
	types.Vars{},
	types.Payload{},
	types.BaseAction{},
	types.Collection{},

	// EC2
	types.EC2Action{},
	types.EC2Config{},

	// EventBridge
	types.EventBridgeAction{},
	types.EventBridgeConfig{},
	types.EventBridgeOutput{},
	types.EventBridgeEntryOutput{},

	// Lambda
	types.LambdaAction{},
	types.LambdaConfig{},
	types.LambdaOutput{},

	// RDS
	types.RDSAction{},
	types.RDSConfig{},

	// SES
	types.SESAction{},
	types.SESConfig{},

	// SFN
	types.SFNAction{},
	types.SFNConfig{},

	// SNS
	types.SNSAction{},
	types.SNSConfig{},
	types.SNSMessageAttribute{},
	types.SNSOutput{},

	// SQS
	types.SQSAction{},
	types.SQSConfig{},
	types.SQSMessageAttrVal{},

	// Output
	types.ActionOutput{},
	types.ResponseMetadata{},
	types.ActionError{},
}

func main() {
	var sb strings.Builder
	sb.WriteString("// CIG GENERATED CODE - DO NOT EDIT\n")
	sb.WriteString("// Generated by cmd/tsgen/main.go\n\n")

	// Map to keep track of generated types to avoid duplicates if referenced recursively
	seen := make(map[string]bool)

	for _, t := range typeRegistry {
		rt := reflect.TypeOf(t)
		generateType(&sb, rt, seen)
	}

	// Output file
	// Ensure directory exists
	if err := os.MkdirAll("frontend/src/lib", 0755); err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
	}

	outputPath := "frontend/src/lib/go-types.ts"
	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Successfully generated types at %s\n", outputPath)
}

func generateType(sb *strings.Builder, t reflect.Type, seen map[string]bool) {
	if t.Kind() == reflect.Ptr {
		t = t.Elem() // Dereference pointer
	}
	if t.Kind() != reflect.Struct {
		return
	}

	typeName := t.Name()
	if typeName == "" || seen[typeName] {
		return
	}
	seen[typeName] = true

	sb.WriteString(fmt.Sprintf("export interface %s {\n", typeName))

	printStructFields(sb, t)

	sb.WriteString("}\n\n")
}

func printStructFields(sb *strings.Builder, t reflect.Type) {
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)

		// Handle embedded structs (Anonymous fields)
		if field.Anonymous {
			embeddedType := field.Type
			if embeddedType.Kind() == reflect.Ptr {
				embeddedType = embeddedType.Elem()
			}
			if embeddedType.Kind() == reflect.Struct {
				printStructFields(sb, embeddedType)
			}
			continue
		}

		jsonTag := field.Tag.Get("json")
		if jsonTag == "-" {
			continue
		}

		name := field.Name
		isOptional := false

		if jsonTag != "" {
			parts := strings.Split(jsonTag, ",")
			name = parts[0]
			if len(parts) > 1 {
				for _, p := range parts[1:] {
					if p == "omitempty" {
						isOptional = true
					}
				}
			}
		}

		if field.PkgPath != "" {
			continue // private
		}

		tsType := toTSType(field.Type)
		suffix := ""
		if isOptional {
			suffix = "?"
		}
		sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", name, suffix, tsType))
	}
}

func toTSType(t reflect.Type) string {
	if t.Kind() == reflect.Ptr {
		t = t.Elem() // Dereference
	}

	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Struct:
		// Check if it is time.Time
		if t.PkgPath() == "time" && t.Name() == "Time" {
			return "string"
		}
		return t.Name()
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return "string" // []byte
		}
		return toTSType(t.Elem()) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", toTSType(t.Key()), toTSType(t.Elem()))
	case reflect.Interface:
		return "any"
	default:
		return "any"
	}
}
