// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEnvVar(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddEnvVar'](arg1, arg2, arg3, arg4);
}

export function CreateAction(arg1) {
  return window['go']['main']['App']['CreateAction'](arg1);
}

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3);
}

export function CreateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2);
}

export function DeleteAction(arg1) {
  return window['go']['main']['App']['DeleteAction'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteEnvVar'](arg1, arg2, arg3);
}

export function GetAction(arg1) {
  return window['go']['main']['App']['GetAction'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetEnvironment(arg1, arg2) {
  return window['go']['main']['App']['GetEnvironment'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateAction(arg1) {
  return window['go']['main']['App']['UpdateAction'](arg1);
}

export function UpdateCollection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateEnvVar(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateEnvVar'](arg1, arg2, arg3, arg4);
}
