// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';

export function CreateCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function GetCollection(arg1:string):Promise<collection.CollectionResponse>;

export function Greet(arg1:string):Promise<string>;

export function UpdateCollection(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;
