// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collection} from '../models';
import {types} from '../models';

export function AddEnvVar(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateAction(arg1:collection.CreateActionInput):Promise<void>;

export function CreateCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateEnvironment(arg1:string,arg2:string):Promise<void>;

export function DeleteAction(arg1:collection.GetActionInput):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvVar(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAction(arg1:collection.GetActionInput):Promise<any>;

export function GetCollection(arg1:string):Promise<collection.CollectionResponse>;

export function GetEnvironment(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function UpdateAction(arg1:collection.UpdateActionInput):Promise<void>;

export function UpdateCollection(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>,arg5:types.Credentials):Promise<void>;

export function UpdateEnvVar(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
