// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateCollection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCollection'](arg1, arg2, arg3, arg4);
}
