// CIG GENERATED CODE - DO NOT EDIT
// Generated by cmd/tsgen/main.go

export interface Metadata {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
}

export interface Vars {
  pre: Record<string, any>;
}

export interface Payload {
  data?: string;
  file?: string;
}

export interface BaseAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
}

export interface Collection {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  credentials: Credentials;
  pre: Record<string, any>;
}

export interface EC2Action {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  ec2: EC2Config;
}

export interface EC2Config {
  instance_ids: string[];
  filters?: Record<string, string[]>;
  hibernate: boolean;
  force: boolean;
  dry_run: boolean;
}

export interface EventBridgeAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  eventbridge: EventBridgeConfig;
}

export interface EventBridgeConfig {
  bus_name: string;
  source: string;
  detail_type: string;
  resources?: string[];
  trace_header?: string;
}

export interface EventBridgeOutput {
  FailedEntryCount: number;
  Entries: EventBridgeEntryOutput[];
}

export interface EventBridgeEntryOutput {
  EventId: string;
  ErrorCode?: string;
  ErrorMessage?: string;
}

export interface LambdaAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  lambda: LambdaConfig;
}

export interface LambdaConfig {
  function_name: string;
  invocation_type: string;
  qualifier?: string;
  client_context?: Record<string, any>;
}

export interface LambdaOutput {
  status_code: number;
  executed_version: string;
  payload: Record<string, any>;
  logs?: string;
}

export interface RDSAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  rds: RDSConfig;
}

export interface RDSConfig {
  db_instance_identifier: string;
  filters?: Record<string, string[]>;
  db_snapshot_identifier?: string;
  force_failover: boolean;
}

export interface SESAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  ses: SESConfig;
}

export interface SESConfig {
  source: string;
  to_addresses: string[];
  cc_addresses?: string[];
  bcc_addresses?: string[];
  subject: string;
  html_body?: string;
  text_body?: string;
  email_address?: string;
}

export interface SFNAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  sfn: SFNConfig;
}

export interface SFNConfig {
  state_machine_arn?: string;
  name?: string;
  execution_arn?: string;
  error?: string;
  cause?: string;
}

export interface SNSAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  sns: SNSConfig;
}

export interface SNSConfig {
  topic_arn?: string;
  target_arn?: string;
  phone_number?: string;
  subject?: string;
  message_structure?: string;
  message_group_id?: string;
  message_deduplication_id?: string;
  message_attributes?: Record<string, SNSMessageAttribute>;
}

export interface SNSMessageAttribute {
  DataType: string;
  StringValue: string;
  BinaryValue: string;
}

export interface SNSOutput {
  message_id: string;
  sequence_number?: string;
}

export interface SQSAction {
  version: string;
  kind: string;
  description: string;
  timeout_ms?: number;
  pre: Record<string, any>;
  credentials: Credentials;
  payload: Payload;
  sqs: SQSConfig;
}

export interface SQSConfig {
  queue_url: string;
  delay_seconds: number;
  message_group_id?: string;
  message_deduplication_id?: string;
  max_number_of_messages: number;
  wait_time_seconds: number;
  visibility_timeout: number;
  attribute_names?: string[];
  message_attribute_names?: string[];
  receipt_handle?: string;
  source_arn?: string;
  destination_arn?: string;
  max_messages_per_second: number;
  message_attributes?: Record<string, SQSMessageAttrVal>;
}

export interface SQSMessageAttrVal {
  DataType: string;
  StringValue: string;
  BinaryValue: string;
}

export interface ActionOutput {
  metadata: ResponseMetadata;
  data?: any;
  error?: ActionError;
}

export interface ResponseMetadata {
  status: string;
  action: string;
  timestamp: string;
  profile?: string;
  region?: string;
}

export interface ActionError {
  code: string;
  message: string;
}

