name: Winget Release
on:
  release:
    types: [published]

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - name: Winget Releaser
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: jpalaniselvam.myna
          installers-regex: '\.zip$'
          token: ${{ secrets.RELEASE_TOKEN }}
